"""add sponsor impression tracking"""
from alembic import op
import sqlalchemy as sa
revision="20260920_0030";down_revision="20260918_0029";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("sponsor_impressions",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("club_id",sa.Uuid(),nullable=False),sa.Column("game_id",sa.Uuid(),nullable=False),sa.Column("sponsor_id",sa.Uuid(),nullable=True),sa.Column("sponsor_name",sa.String(255),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True),nullable=False),sa.Column("ended_at",sa.DateTime(timezone=True),nullable=True),sa.Column("duration_seconds",sa.Integer(),nullable=True),sa.Column("trigger",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("duration_seconds IS NULL OR duration_seconds >= 0",name="ck_sponsor_impressions_duration_nonnegative"),sa.ForeignKeyConstraint(["club_id"],["clubs.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["game_id"],["games.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["sponsor_id"],["sponsors.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"))
    op.create_index("ix_sponsor_impressions_club_id","sponsor_impressions",["club_id"]);op.create_index("ix_sponsor_impressions_game_id","sponsor_impressions",["game_id"]);op.create_index("ix_sponsor_impressions_sponsor_id","sponsor_impressions",["sponsor_id"])
    op.create_table("game_sponsor_tracking_states",sa.Column("game_id",sa.Uuid(),nullable=False),sa.Column("active_sponsor_id",sa.Uuid(),nullable=True),sa.Column("active_impression_id",sa.Uuid(),nullable=True),sa.Column("tracking_active",sa.Boolean(),server_default=sa.false(),nullable=False),sa.Column("last_reconciled_at",sa.DateTime(timezone=True),nullable=False),sa.Column("version",sa.Integer(),server_default="1",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["game_id"],["games.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["active_sponsor_id"],["sponsors.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["active_impression_id"],["sponsor_impressions.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("game_id"))
def downgrade():
    op.drop_table("game_sponsor_tracking_states");op.drop_index("ix_sponsor_impressions_sponsor_id",table_name="sponsor_impressions");op.drop_index("ix_sponsor_impressions_game_id",table_name="sponsor_impressions");op.drop_index("ix_sponsor_impressions_club_id",table_name="sponsor_impressions");op.drop_table("sponsor_impressions")
