#!/usr/bin/env python3
from pathlib import Path
def rep(path,old,new):
 p=Path(path);t=p.read_text()
 if new in t: print('OK:',path);return
 if old not in t: raise SystemExit('ERROR: M19-C anchor missing: '+path)
 p.write_text(t.replace(old,new,1));print('UPDATED:',path)
rep('app/api/control.py','from app.services.effective_branding_service import get_effective_club_branding\n','from app.services.effective_branding_service import get_effective_club_branding\nfrom app.services.effective_game_sponsor_service import get_effective_game_sponsors\n')
rep('app/api/control.py','        "branding": await get_effective_club_branding(db, game.club_id),\n','        "branding": await get_effective_club_branding(db, game.club_id),\n        "sponsors": await get_effective_game_sponsors(db, game.id, game.club_id),\n')
rep('templates/overlay/game.html','  <link rel="stylesheet" href="/static/css/branding-broadcast-m18g3.css?v=859dedf">\n','  <link rel="stylesheet" href="/static/css/branding-broadcast-m18g3.css?v=859dedf">\n  <link rel="stylesheet" href="/static/css/overlay-sponsors-m19d.css?v=m19d-1">\n')
old='''    <aside id="ssl-network-bug"\n           class="ssl-network-bug"\n           aria-label="Powered by ScoreStreamLive">\n      <img\n        class="ssl-network-bug-logo"\n        src="/static/brand/scorestreamlive-mark.svg?v=m17h-1"\n        alt="">\n      <div class="ssl-network-bug-copy">\n        <span>Powered by</span>\n        <strong>ScoreStreamLive</strong>\n      </div>\n    </aside>\n'''
new='''    <aside id="sponsor-zone" class="sponsor-zone is-fallback" aria-label="Game sponsor">\n      <div id="sponsor-stage" class="sponsor-stage hidden"><img id="sponsor-logo" class="sponsor-logo" alt=""></div>\n      <div id="sponsor-fallback" class="sponsor-fallback"><img class="sponsor-fallback-logo" src="/static/brand/scorestreamlive-mark.svg?v=m17h-1" alt=""><div class="sponsor-fallback-copy"><span>Powered by</span><strong>ScoreStreamLive</strong></div></div>\n      <div class="sponsor-powered-by">Powered by ScoreStreamLive</div>\n    </aside>\n'''
rep('templates/overlay/game.html',old,new)
rep('templates/overlay/game.html','<script type="module" src="/static/js/overlay/overlay.js?v=859dedf"></script>','<script type="module" src="/static/js/overlay/overlay.js?v=m19d-1"></script>')
rep('static/js/overlay/overlay.js','const DEFAULT_SECONDARY = "#FFFFFF";\n','const DEFAULT_SECONDARY = "#FFFFFF";\nconst DEFAULT_SPONSOR_ROTATION_MS = 10000;\nconst SPONSOR_FADE_MS = 300;\n')
rep('static/js/overlay/overlay.js','  branding: null,\n','  branding: null,\n  sponsors: [],\n  sponsorIndex: 0,\n  sponsorRotationTimer: null,\n  sponsorSwapTimeout: null,\n')
rep('static/js/overlay/overlay.js','  const networkBug = document.querySelector(".ssl-network-bug");\n','  const networkBug = byId("sponsor-zone");\n')
anchor='function applyOverlayTeamBrand(side, team) {\n'
code='''function stopSponsorRotation() {\n  if (state.sponsorRotationTimer !== null) { window.clearInterval(state.sponsorRotationTimer); state.sponsorRotationTimer = null; }\n  if (state.sponsorSwapTimeout !== null) { window.clearTimeout(state.sponsorSwapTimeout); state.sponsorSwapTimeout = null; }\n}\nfunction showSponsorFallback() {\n  stopSponsorRotation(); const zone=byId("sponsor-zone"),stage=byId("sponsor-stage"),fallback=byId("sponsor-fallback"),logo=byId("sponsor-logo"); if(!zone||!stage||!fallback||!logo)return;\n  zone.classList.add("is-fallback");stage.classList.add("hidden");fallback.classList.remove("hidden");logo.classList.remove("sponsor-fading");logo.removeAttribute("src");logo.alt="";\n}\nfunction usableSponsors(){return(state.sponsors||[]).filter(s=>String(s?.artwork_url||"").trim());}\nfunction displaySponsorAt(index,animate=false){\n const sponsors=usableSponsors();if(!sponsors.length){showSponsorFallback();return;} const zone=byId("sponsor-zone"),stage=byId("sponsor-stage"),fallback=byId("sponsor-fallback"),logo=byId("sponsor-logo");if(!zone||!stage||!fallback||!logo)return;\n state.sponsorIndex=((index%sponsors.length)+sponsors.length)%sponsors.length;const sponsor=sponsors[state.sponsorIndex];\n const applyImage=()=>{logo.src=sponsor.artwork_url;logo.alt=`${sponsor.name||"Sponsor"} logo`;logo.onerror=()=>{const id=String(sponsor.id||"");state.sponsors=(state.sponsors||[]).filter(x=>String(x.id||"")!==id);syncSponsorRotation();};zone.classList.remove("is-fallback");fallback.classList.add("hidden");stage.classList.remove("hidden");requestAnimationFrame(()=>logo.classList.remove("sponsor-fading"));};\n if(!animate||!logo.getAttribute("src")){applyImage();return;} logo.classList.add("sponsor-fading");if(state.sponsorSwapTimeout!==null)window.clearTimeout(state.sponsorSwapTimeout);state.sponsorSwapTimeout=window.setTimeout(()=>{state.sponsorSwapTimeout=null;applyImage();},SPONSOR_FADE_MS);\n}\nfunction syncSponsorRotation(){stopSponsorRotation();const sponsors=usableSponsors();if(!sponsors.length){showSponsorFallback();return;}if(state.sponsorIndex>=sponsors.length)state.sponsorIndex=0;displaySponsorAt(state.sponsorIndex,false);if(sponsors.length>1)state.sponsorRotationTimer=window.setInterval(()=>{const current=usableSponsors();if(current.length<=1){syncSponsorRotation();return;}displaySponsorAt(state.sponsorIndex+1,true);},DEFAULT_SPONSOR_ROTATION_MS);}\n\n'''
rep('static/js/overlay/overlay.js',anchor,code+anchor)
rep('static/js/overlay/overlay.js','  state.branding = snapshot.branding || null;\n','  state.branding = snapshot.branding || null;\n  state.sponsors = snapshot.sponsors || [];\n  state.sponsorIndex = 0;\n  syncSponsorRotation();\n')
print('M19-D integrations applied.')
