from pathlib import Path
def patch(path,old,new):
 p=Path(path);t=p.read_text()
 if new in t: print("already applied:",path); return
 if old not in t: raise SystemExit("HF7 integration anchor not found: "+path)
 p.write_text(t.replace(old,new,1)); print("patched:",path)

patch("app/models/__init__.py",'from app.models.game_broadcast_presentation import GameBroadcastPresentation\n','from app.models.game_broadcast_presentation import GameBroadcastPresentation\nfrom app.models.game_halftime_slideshow import GameHalftimeSlideshow, GameHalftimeSlideshowSlide\n')
patch("app/models/__init__.py",'    "GameBroadcastPresentation",\n','    "GameBroadcastPresentation",\n    "GameHalftimeSlideshow",\n    "GameHalftimeSlideshowSlide",\n')
patch("app/main.py",'from app.api.game_broadcast_presentation import router as game_broadcast_presentation_router\n','from app.api.game_broadcast_presentation import router as game_broadcast_presentation_router\nfrom app.api.game_halftime_slideshow import router as game_halftime_slideshow_router\n')
patch("app/main.py",'app.include_router(game_broadcast_presentation_router)\n','app.include_router(game_broadcast_presentation_router)\napp.include_router(game_halftime_slideshow_router)\n')
patch("app/models/game_broadcast_presentation.py",'''CheckConstraint("scene IN ('intro','live','advertisement','summary','thank_you')",name="ck_game_broadcast_presentations_scene")''','''CheckConstraint("scene IN ('intro','live','advertisement','halftime_slideshow','summary','thank_you')",name="ck_game_broadcast_presentations_scene")''')

p=Path("app/services/game_broadcast_presentation_service.py");t=p.read_text()
if "GameHalftimeSlideshowSlide" not in t:
 t=t.replace('from app.models.game_broadcast_presentation import GameBroadcastPresentation\n','from app.models.game_broadcast_presentation import GameBroadcastPresentation\nfrom app.models.game_halftime_slideshow import GameHalftimeSlideshow,GameHalftimeSlideshowSlide\nfrom app.models.broadcast_artwork import BroadcastArtwork\nfrom sqlalchemy import select\n')
 t=t.replace('VALID_SCENES={"intro","live","advertisement","summary","thank_you"}','VALID_SCENES={"intro","live","advertisement","halftime_slideshow","summary","thank_you"}')
 old='row=await db.get(GameBroadcastPresentation,game_id);intro_available=bool(game.intro_enabled and game.intro_image_url);advertisement_available=bool(game.advertisement_enabled and game.advertisement_image_url);thank_available=bool(game.thank_you_enabled and game.thank_you_image_url);scene=row.scene if row else ("intro" if intro_available else "live")'
 new='row=await db.get(GameBroadcastPresentation,game_id);intro_available=bool(game.intro_enabled and game.intro_image_url);advertisement_available=bool(game.advertisement_enabled and game.advertisement_image_url);thank_available=bool(game.thank_you_enabled and game.thank_you_image_url);slideshow=await db.get(GameHalftimeSlideshow,game_id);slide_pairs=(await db.execute(select(GameHalftimeSlideshowSlide,BroadcastArtwork).join(BroadcastArtwork,BroadcastArtwork.id==GameHalftimeSlideshowSlide.artwork_id).where(GameHalftimeSlideshowSlide.game_id==game_id).order_by(GameHalftimeSlideshowSlide.position))).all();slideshow_available=bool(slideshow and slideshow.enabled and slide_pairs);scene=row.scene if row else ("intro" if intro_available else "live")'
 if old not in t: raise SystemExit("HF7 serializer anchor 1 not found")
 t=t.replace(old,new,1)
 t=t.replace('if scene=="thank_you" and not thank_available:scene="live"\n','if scene=="thank_you" and not thank_available:scene="live"\n if scene=="halftime_slideshow" and not slideshow_available:scene="live"\n',1)
 old='return {"game_id":str(game.id),"scene":scene,"version":row.version if row else 0,"updated_at":row.updated_at if row else (game.intro_updated_at or game.advertisement_updated_at or game.thank_you_updated_at),"intro":{"enabled":bool(game.intro_enabled),"image_url":_versioned_asset_url(game.intro_image_url,game.intro_updated_at) if intro_available else None},"advertisement":{"enabled":bool(game.advertisement_enabled),"image_url":_versioned_asset_url(game.advertisement_image_url,game.advertisement_updated_at) if advertisement_available else None},"thank_you":{"enabled":bool(game.thank_you_enabled),"image_url":_versioned_asset_url(game.thank_you_image_url,game.thank_you_updated_at) if thank_available else None}}'
 new='return {"game_id":str(game.id),"scene":scene,"version":row.version if row else 0,"updated_at":row.updated_at if row else (game.intro_updated_at or game.advertisement_updated_at or game.thank_you_updated_at),"intro":{"enabled":bool(game.intro_enabled),"image_url":_versioned_asset_url(game.intro_image_url,game.intro_updated_at) if intro_available else None},"advertisement":{"enabled":bool(game.advertisement_enabled),"image_url":_versioned_asset_url(game.advertisement_image_url,game.advertisement_updated_at) if advertisement_available else None},"halftime_slideshow":{"enabled":bool(slideshow and slideshow.enabled),"interval_seconds":slideshow.interval_seconds if slideshow else 10,"slides":[{"id":str(s.id),"artwork_id":str(a.id),"name":a.name,"image_url":a.image_url,"position":s.position} for s,a in slide_pairs]},"thank_you":{"enabled":bool(game.thank_you_enabled),"image_url":_versioned_asset_url(game.thank_you_image_url,game.thank_you_updated_at) if thank_available else None}}'
 if old not in t: raise SystemExit("HF7 serializer return anchor not found")
 t=t.replace(old,new,1)
 anchor='if scene=="thank_you" and not(game.thank_you_enabled and game.thank_you_image_url):raise HTTPException(409,"Thank You Screen is not available")\n'
 add=anchor+' if scene=="halftime_slideshow":\n  slideshow=await db.get(GameHalftimeSlideshow,game_id);has_slide=(await db.execute(select(GameHalftimeSlideshowSlide.id).where(GameHalftimeSlideshowSlide.game_id==game_id).limit(1))).scalar_one_or_none()\n  if not slideshow or not slideshow.enabled or has_slide is None:raise HTTPException(409,"Halftime Slideshow is not available")\n'
 if anchor not in t: raise SystemExit("HF7 scene availability anchor not found")
 t=t.replace(anchor,add,1);p.write_text(t);print("patched: broadcast service")

patch("app/api/broadcast_artwork.py",'from app.models.game import Game\n','from app.models.game import Game\nfrom app.models.game_halftime_slideshow import GameHalftimeSlideshowSlide\n')
patch("app/api/broadcast_artwork.py",'    if used is not None:raise HTTPException(409,"Artwork is currently assigned to one or more games")\n','    if used is not None:raise HTTPException(409,"Artwork is currently assigned to one or more games")\n    slide_used=(await db.execute(select(GameHalftimeSlideshowSlide.id).where(GameHalftimeSlideshowSlide.artwork_id==a.id).limit(1))).scalar_one_or_none()\n    if slide_used is not None:raise HTTPException(409,"Artwork is currently assigned to a Halftime Slideshow")\n')

patch("templates/games/detail.html",'  <link rel="stylesheet" href="/static/css/broadcast-artwork-m19hf6.css?v=m19hf6-2">\n','  <link rel="stylesheet" href="/static/css/broadcast-artwork-m19hf6.css?v=m19hf6-2">\n  <link rel="stylesheet" href="/static/css/halftime-slideshow-m19hf7.css?v=m19hf7-1">\n')
block='    <section id="m19hf7-halftime-panel" class="game-intro-panel hidden">\n      <div><span class="eyebrow">HALFTIME PRESENTATION</span><h2>Halftime Slideshow</h2><p>Select reusable Broadcast Artwork, arrange the order, and choose how long each image stays on screen.</p></div>\n      <div class="m19hf7-controls"><label><input id="m19hf7-enabled" type="checkbox"> Enable Halftime Slideshow</label><label>Slide Interval <select id="m19hf7-interval"><option value="5">5 seconds</option><option value="10">10 seconds</option><option value="15">15 seconds</option><option value="20">20 seconds</option><option value="30">30 seconds</option></select></label><button id="m19hf7-save" class="button button-secondary" type="button">Save Slideshow Settings</button></div>\n      <div class="m19hf7-add-row"><select id="m19hf7-artwork"></select><button id="m19hf7-add" class="button button-secondary" type="button">Add to Slideshow</button></div>\n      <div id="m19hf7-slide-list" class="m19hf7-slide-list"></div><span id="m19hf7-message" class="game-intro-message" role="status"></span>\n    </section>\n\n'
patch("templates/games/detail.html",'    <section id="m19hf1b-thank-you-panel" class="game-intro-panel hidden">\n',block+'    <section id="m19hf1b-thank-you-panel" class="game-intro-panel hidden">\n')
patch("templates/games/detail.html",'  <script type="module">import {loadGameAdvertisement} from "/static/js/games/game-advertisement-m19hf2.js?v=m19hf2-1"; loadGameAdvertisement(document.body.dataset.gameId);</script>\n','  <script type="module">import {loadGameAdvertisement} from "/static/js/games/game-advertisement-m19hf2.js?v=m19hf2-1"; loadGameAdvertisement(document.body.dataset.gameId);</script>\n  <script type="module">import {loadHalftimeSlideshow} from "/static/js/games/halftime-slideshow-m19hf7.js?v=m19hf7-1"; loadHalftimeSlideshow(document.body.dataset.gameId);</script>\n')
patch("templates/control/game.html",'            <button id="m19hf2-show-advertisement" class="secondary-button" type="button">Advertisement</button>\n','            <button id="m19hf2-show-advertisement" class="secondary-button" type="button">Advertisement</button>\n            <button id="m19hf7-show-halftime" class="secondary-button" type="button">Halftime Slideshow</button>\n')

p=Path("static/js/control/broadcast-presentation-m19h.js");t=p.read_text()
if "m19hf7-show-halftime" not in t:
 t=t.replace('  const summary = document.getElementById("m19hf1b-show-summary");','  const halftime = document.getElementById("m19hf7-show-halftime");\n  const summary = document.getElementById("m19hf1b-show-summary");')
 t=t.replace('    thankYou.disabled = !state?.thank_you?.image_url;','    halftime.disabled = !(state?.halftime_slideshow?.enabled && state?.halftime_slideshow?.slides?.length);\n    thankYou.disabled = !state?.thank_you?.image_url;')
 t=t.replace('      ["advertisement", advertisement],\n      ["summary", summary],','      ["advertisement", advertisement],\n      ["halftime_slideshow", halftime],\n      ["summary", summary],')
 t=t.replace('        advertisement: "Advertisement is live.",\n        summary:','        advertisement: "Advertisement is live.",\n        halftime_slideshow: "Halftime Slideshow is live.",\n        summary:')
 t=t.replace('  advertisement.onclick = () => setScene("advertisement");\n','  advertisement.onclick = () => setScene("advertisement");\n  halftime.onclick = () => setScene("halftime_slideshow");\n')
 p.write_text(t);print("patched: control JS")

patch("templates/stream/game.html",'    <div id="advertisement-scene" class="scene hidden"><img id="advertisement-image" alt="Game advertisement"></div>\n','    <div id="advertisement-scene" class="scene hidden"><img id="advertisement-image" alt="Game advertisement"></div>\n    <div id="halftime-slideshow-scene" class="scene hidden"><img id="halftime-slideshow-image" alt="Halftime slideshow"></div>\n')
patch("templates/stream/game.html",'  <link rel="stylesheet" href="/static/css/broadcast-m19h.css?v=m19hf2-1">\n','  <link rel="stylesheet" href="/static/css/broadcast-m19h.css?v=m19hf7-1">\n')
patch("templates/stream/game.html",'  <script type="module" src="/static/js/broadcast/game-m19h.js?v=m19hf2-1"></script>\n','  <script type="module" src="/static/js/broadcast/game-m19h.js?v=m19hf7-1"></script>\n')
patch("static/css/broadcast-m19h.css",'#intro-scene,#advertisement-scene,#thank-you-scene','#intro-scene,#advertisement-scene,#halftime-slideshow-scene,#thank-you-scene')
patch("static/css/broadcast-m19h.css",'#intro-image,#advertisement-image,#thank-you-image','#intro-image,#advertisement-image,#halftime-slideshow-image,#thank-you-image')
print("M19 HF7 integrations applied.")
