from pathlib import Path

def patch(path,old,new):
 p=Path(path);s=p.read_text()
 if new in s:return
 if old not in s:raise SystemExit(f"M19-H anchor not found: {path}: {old[:90]!r}")
 p.write_text(s.replace(old,new,1))

patch('app/models/game.py','    broadcast_message: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)\n','    broadcast_message: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)\n    intro_image_url: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)\n    intro_enabled: Mapped[bool] = mapped_column(nullable=False, default=False)\n    intro_updated_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)\n')
patch('app/models/__init__.py','from app.models.game_sponsor_tracking_state import GameSponsorTrackingState\n','from app.models.game_sponsor_tracking_state import GameSponsorTrackingState\nfrom app.models.game_broadcast_presentation import GameBroadcastPresentation\n')
patch('app/models/__init__.py','    "GameSponsorTrackingState",\n','    "GameSponsorTrackingState",\n    "GameBroadcastPresentation",\n')
patch('app/config.py','    SPONSOR_ARTWORK_MAX_BYTES: int=_get_sponsor_artwork_max_bytes()\n','    SPONSOR_ARTWORK_MAX_BYTES: int=_get_sponsor_artwork_max_bytes()\n    GAME_INTRO_STORAGE_DIR: str=os.getenv("GAME_INTRO_STORAGE_DIR","static/uploads/game-intros")\n    GAME_INTRO_MAX_BYTES: int=_get_positive_int("GAME_INTRO_MAX_BYTES",5*1024*1024)\n')
patch('app/main.py','from app.api.sponsor_reports import router as sponsor_reports_router\n','from app.api.sponsor_reports import router as sponsor_reports_router\nfrom app.api.game_intro import router as game_intro_router\nfrom app.api.game_broadcast_presentation import router as game_broadcast_presentation_router\n')
patch('app/main.py','from app.services.sponsor_artwork_storage import ensure_storage_dir as ensure_sponsor_artwork_storage_dir\n','from app.services.sponsor_artwork_storage import ensure_storage_dir as ensure_sponsor_artwork_storage_dir\nfrom app.services.game_intro_artwork_storage import ensure_storage_dir as ensure_game_intro_storage_dir\n')
patch('app/main.py','from app.web.game_detail import router as game_detail_web_router\n','from app.web.game_detail import router as game_detail_web_router\nfrom app.web.broadcast import router as broadcast_web_router\n')
patch('app/main.py','    sponsor_dir = ensure_sponsor_artwork_storage_dir()\n','    intro_dir = ensure_game_intro_storage_dir()\n    logger.info("Game intro storage ready — path=%s max_bytes=%s", intro_dir, settings.GAME_INTRO_MAX_BYTES, extra={"event":"game_intro.storage.ready"})\n\n    sponsor_dir = ensure_sponsor_artwork_storage_dir()\n')
patch('app/main.py','app.include_router(sponsor_reports_router)\n','app.include_router(sponsor_reports_router)\napp.include_router(game_intro_router)\napp.include_router(game_broadcast_presentation_router)\n')
patch('app/main.py','app.include_router(game_detail_web_router)\n','app.include_router(game_detail_web_router)\napp.include_router(broadcast_web_router)\n')
patch('app/api/control.py','from app.services.game_sponsor_presentation_service import serialize_public_presentation\n','from app.services.game_sponsor_presentation_service import serialize_public_presentation\nfrom app.services.game_broadcast_presentation_service import serialize_broadcast_state\n')
patch('app/api/control.py','    return jsonable_encoder(snapshot)\n','    return jsonable_encoder(snapshot)\n\n@router.get("/api/public/games/{game_id}/broadcast-state",include_in_schema=False)\nasync def public_broadcast_state(game_id:uuid.UUID,db:AsyncSession=Depends(get_session)):\n    game=await get_game(db,game_id)\n    if not game or not await effective_club_has_entitlement(db,game.club_id,BROADCAST_OVERLAY): deny_not_found("Game")\n    return jsonable_encoder(await serialize_broadcast_state(db,game_id))\n')
patch('docker-compose.yml','      - SPONSOR_ARTWORK_STORAGE_DIR=/home/appuser/app/static/uploads/sponsor-artwork\n','      - SPONSOR_ARTWORK_STORAGE_DIR=/home/appuser/app/static/uploads/sponsor-artwork\n      - GAME_INTRO_STORAGE_DIR=/home/appuser/app/static/uploads/game-intros\n')
patch('docker-compose.yml','      - sponsor_artwork_data:/home/appuser/app/static/uploads/sponsor-artwork\n','      - sponsor_artwork_data:/home/appuser/app/static/uploads/sponsor-artwork\n      - game_intro_data:/home/appuser/app/static/uploads/game-intros\n')
patch('docker-compose.yml','  sponsor_artwork_data:\n','  sponsor_artwork_data:\n  game_intro_data:\n')
patch('Dockerfile','      ./static/uploads/sponsor-artwork && \\\n','      ./static/uploads/sponsor-artwork \\\n      ./static/uploads/game-intros && \\\n')
patch('templates/games/detail.html','  <link rel="stylesheet" href="/static/css/sponsor-report-m19g.css?v=m19g-1">\n','  <link rel="stylesheet" href="/static/css/sponsor-report-m19g.css?v=m19g-1">\n  <link rel="stylesheet" href="/static/css/game-intro-m19h.css?v=m19h-1">\n')
patch('templates/games/detail.html','    <section id="game-sponsors-panel" class="game-sponsors-panel hidden">\n','    <section id="m19h-intro-panel" class="game-intro-panel hidden">\n      <div><span class="eyebrow">STREAM WELCOME SCREEN</span><h2>Per-Game Broadcast Intro</h2><p>Recommended 16:9 artwork, 1280×720 or higher.</p></div>\n      <div class="game-intro-grid"><img id="m19h-intro-preview" class="game-intro-preview" alt="Welcome Screen preview" hidden><div class="game-intro-actions"><label class="button button-secondary">Upload / Replace Image<input id="m19h-intro-upload" type="file" accept="image/png,image/jpeg,image/webp" hidden></label><label><input id="m19h-intro-enabled" type="checkbox"> Enable Welcome Screen</label><button id="m19h-intro-remove" class="button button-secondary" type="button">Remove Image</button><span id="m19h-intro-message" class="game-intro-message" role="status"></span></div></div>\n    </section>\n\n    <section id="game-sponsors-panel" class="game-sponsors-panel hidden">\n')
patch('templates/games/detail.html','  <script type="module">import {loadSponsorReport} from "/static/js/games/sponsor-report-m19g.js?v=m19g-1"; loadSponsorReport(document.body.dataset.gameId);</script>\n','  <script type="module">import {loadSponsorReport} from "/static/js/games/sponsor-report-m19g.js?v=m19g-1"; loadSponsorReport(document.body.dataset.gameId);</script>\n  <script type="module">import {loadGameIntro} from "/static/js/games/game-intro-m19h.js?v=m19h-1"; loadGameIntro(document.body.dataset.gameId);</script>\n')
# Modify existing detail JS rather than competing click handlers.
patch('static/js/games/detail.js','  byId("overlay-link").href = `/overlay/games/${game.id}`;\n','  byId("overlay-link").href = `/broadcast/games/${game.id}`;\n  byId("overlay-link").querySelector("strong").textContent = "Open Broadcast";\n')
patch('static/js/games/detail.js','  const overlayUrl = `${window.location.origin}/overlay/games/${state.game.id}`;\n','  const overlayUrl = `${window.location.origin}/broadcast/games/${state.game.id}`;\n')
patch('static/js/games/detail.js','  notice.textContent = "Overlay URL copied to clipboard.";\n','  notice.textContent = "Broadcast URL copied to clipboard.";\n')
patch('templates/games/detail.html','        <button id="copy-overlay-url" class="button button-secondary" type="button">Copy Overlay URL</button>\n','        <button id="copy-overlay-url" class="button button-secondary" type="button">Copy Broadcast URL</button>\n')
patch('templates/control/game.html','  <link rel="stylesheet" href="/static/css/control-sponsors-m19e.css?v=m19e-1">\n','  <link rel="stylesheet" href="/static/css/control-sponsors-m19e.css?v=m19e-1">\n  <link rel="stylesheet" href="/static/css/control-broadcast-m19h.css?v=m19h-1">\n')
anchor='        <article id="m19e-sponsor-controls" class="card operator-card sponsor-live-card">'
patch('templates/control/game.html',anchor,'        <article id="m19h-broadcast-controls" class="card operator-card"><div class="card-header"><h2>Broadcast Scene</h2><span id="m19h-scene-state" class="command-status">LOADING</span></div><p class="muted">Switch the stable Broadcast URL between the Welcome Screen and Live Game.</p><div class="m19h-broadcast-actions"><button id="m19h-show-intro" class="secondary-button" type="button">Show Welcome</button><button id="m19h-go-live" class="primary-action" type="button">Go Live</button></div><div id="m19h-broadcast-message" class="m19h-broadcast-message muted" role="status"></div></article>\n'+anchor)
patch('templates/control/game.html','</body>','<script type="module">import {initBroadcastPresentation} from "/static/js/control/broadcast-presentation-m19h.js?v=m19h-1"; initBroadcastPresentation(document.body.dataset.gameId);</script>\n</body>')
print('M19-H integrations applied')
