#!/usr/bin/env python3
from pathlib import Path
def edit(path,old,new):
 p=Path(path);s=p.read_text()
 if new in s:return
 if old not in s:raise SystemExit(f"M19-G integration anchor missing: {path}")
 p.write_text(s.replace(old,new,1))
edit("app/models/__init__.py",'from app.models.game_sponsor_presentation import GameSponsorPresentation\n','from app.models.game_sponsor_presentation import GameSponsorPresentation\nfrom app.models.sponsor_impression import SponsorImpression\nfrom app.models.game_sponsor_tracking_state import GameSponsorTrackingState\n')
edit("app/models/__init__.py",'    "GameSponsorPresentation",\n','    "GameSponsorPresentation",\n    "SponsorImpression",\n    "GameSponsorTrackingState",\n')
edit("app/main.py",'from app.api.game_sponsor_presentation import router as game_sponsor_presentation_router\n','from app.api.game_sponsor_presentation import router as game_sponsor_presentation_router\nfrom app.api.sponsor_reports import router as sponsor_reports_router\n')
edit("app/main.py",'app.include_router(game_sponsor_presentation_router)\n','app.include_router(game_sponsor_presentation_router)\napp.include_router(sponsor_reports_router)\n')
edit("app/services/game_lifecycle_service.py",'    now = _utc_now()\n    clock_values, clock_status_rule = _build_clock_values(\n','    now = _utc_now()\n    from app.services.sponsor_impression_service import reconcile_sponsor_tracking\n    await reconcile_sponsor_tracking(db, game_id, at=now, trigger="lifecycle", commit=False)\n    clock_values, clock_status_rule = _build_clock_values(\n')
edit("app/services/game_lifecycle_service.py",'    await db.commit()\n\n    committed_lifecycle = await _reload_lifecycle(db, game_id)\n','    await db.commit()\n\n    await reconcile_sponsor_tracking(db, game_id, at=now, trigger="game_start" if next_phase=="first_half" else ("second_half_start" if next_phase=="second_half" else "lifecycle"), commit=True)\n\n    committed_lifecycle = await _reload_lifecycle(db, game_id)\n')
edit("app/services/game_sponsor_presentation_service.py",'async def update_presentation(db,game_id,data):\n    game,row=await ensure_presentation(db,game_id)\n','async def update_presentation(db,game_id,data):\n    game,row=await ensure_presentation(db,game_id)\n    from app.services.sponsor_impression_service import reconcile_sponsor_tracking\n    now=_now(); await reconcile_sponsor_tracking(db,game_id,at=now,trigger=data.action,commit=True)\n')
edit("app/services/game_sponsor_presentation_service.py",'    row.version+=1; row.updated_at=_now(); await db.commit(); await db.refresh(row); return await serialize_presentation(db,game_id)\n','    row.version+=1; row.updated_at=now; await db.commit(); await db.refresh(row)\n    await reconcile_sponsor_tracking(db,game_id,at=now,trigger=data.action,commit=True)\n    return await serialize_presentation(db,game_id)\n')
edit("templates/games/detail.html",'  <link rel="stylesheet" href="/static/css/game-sponsors-m19c.css?v=m19c-3">\n','  <link rel="stylesheet" href="/static/css/game-sponsors-m19c.css?v=m19c-3">\n  <link rel="stylesheet" href="/static/css/sponsor-report-m19g.css?v=m19g-1">\n')
edit("templates/games/detail.html",'    <section id="readiness-grid" class="readiness-grid hidden">\n','    <section id="sponsor-report-panel" class="sponsor-report-panel hidden">\n      <div class="sponsor-report-heading"><div><span class="eyebrow">SPONSOR PERFORMANCE</span><h2>Tracked Sponsor Appearances</h2><p id="sponsor-report-summary">Loading…</p></div></div>\n      <div id="sponsor-report-body" class="sponsor-report-body"></div>\n    </section>\n\n    <section id="readiness-grid" class="readiness-grid hidden">\n')
edit("templates/games/detail.html",'  <script type="module" src="/static/js/games/detail.js"></script>\n','  <script type="module" src="/static/js/games/detail.js"></script>\n  <script type="module">import {loadSponsorReport} from "/static/js/games/sponsor-report-m19g.js?v=m19g-1"; loadSponsorReport(document.body.dataset.gameId);</script>\n')
print("M19-G integrations applied.")
