#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def patch(path,old,new):
    p=ROOT/path; t=p.read_text()
    if new in t: print(f"PASS already patched {path}"); return
    if old not in t: raise SystemExit(f"M17-D precondition failed: {path}")
    p.write_text(t.replace(old,new,1)); print(f"PASS patched {path}")
patch('app/main.py','from app.api.games import router as games_router\n','from app.api.games import router as games_router\nfrom app.api.invitations import router as invitations_router\n')
patch('app/main.py','from app.web.account import router as account_web_router\n','from app.web.account import router as account_web_router\nfrom app.web.activation import router as activation_web_router\n')
patch('app/main.py','app.include_router(games_router)\n','app.include_router(games_router)\napp.include_router(invitations_router)\n')
patch('app/main.py','app.include_router(account_web_router)\n','app.include_router(account_web_router)\napp.include_router(activation_web_router)\n')
patch('app/config.py','def _get_bool(name: str, default: bool) -> bool:\n','def _get_positive_int(name: str, default: int) -> int:\n    try:\n        value = int(os.getenv(name, str(default)))\n    except (ValueError, TypeError):\n        return default\n    return value if value > 0 else default\n\n\ndef _get_bool(name: str, default: bool) -> bool:\n')
patch('app/config.py','    AUTH_SESSION_COOKIE_SECURE: bool = _get_bool(\n        "AUTH_SESSION_COOKIE_SECURE",\n        os.getenv("APP_ENV", "development") == "production",\n    )\n','    AUTH_SESSION_COOKIE_SECURE: bool = _get_bool(\n        "AUTH_SESSION_COOKIE_SECURE",\n        os.getenv("APP_ENV", "development") == "production",\n    )\n\n    # M17-D invitation/email delivery.\n    PUBLIC_BASE_URL: str = os.getenv("PUBLIC_BASE_URL", "http://localhost:8000")\n    INVITATION_TTL_HOURS: int = _get_positive_int("INVITATION_TTL_HOURS", 72)\n    EMAIL_DELIVERY_MODE: str = os.getenv("EMAIL_DELIVERY_MODE", "log").strip().lower()\n    SMTP_HOST: str = os.getenv("SMTP_HOST", "")\n    SMTP_PORT: int = _get_positive_int("SMTP_PORT", 587)\n    SMTP_USERNAME: str = os.getenv("SMTP_USERNAME", "")\n    SMTP_PASSWORD: str = os.getenv("SMTP_PASSWORD", "")\n    SMTP_USE_TLS: bool = _get_bool("SMTP_USE_TLS", True)\n    EMAIL_FROM_ADDRESS: str = os.getenv("EMAIL_FROM_ADDRESS", "")\n    EMAIL_FROM_NAME: str = os.getenv("EMAIL_FROM_NAME", "ScoreStreamLive")\n')
patch('app/auth/security.py','    if not settings.DB_PASSWORD or settings.DB_PASSWORD == "change-me":\n        findings.append("DB_PASSWORD must not use the development default in production")\n','    if not settings.DB_PASSWORD or settings.DB_PASSWORD == "change-me":\n        findings.append("DB_PASSWORD must not use the development default in production")\n\n    if settings.EMAIL_DELIVERY_MODE != "smtp":\n        findings.append("EMAIL_DELIVERY_MODE must be smtp in production")\n    else:\n        if not settings.SMTP_HOST:\n            findings.append("SMTP_HOST must be configured in production")\n        if not settings.EMAIL_FROM_ADDRESS:\n            findings.append("EMAIL_FROM_ADDRESS must be configured in production")\n        if not settings.PUBLIC_BASE_URL.startswith("https://"):\n            findings.append("PUBLIC_BASE_URL must use https in production")\n')
patch('scripts/validate.sh',"add 'Post-Game Summary & Broadcast Scene' scripts/regression/post_game_summary_broadcast.sh\n","add 'Post-Game Summary & Broadcast Scene' scripts/regression/post_game_summary_broadcast.sh\nadd 'User Invitation & Account Activation' scripts/regression/user_invitation_activation.sh\n")
p=ROOT/'app/api/club_admin.py';t=p.read_text();t=t.replace('    create_club_member,\n','')
s=t.find('class MemberCreate(BaseModel):\n'); e=t.find('\n\nclass MemberUpdate',s) if s!=-1 else -1; t=t[:s]+t[e+2:] if s!=-1 and e!=-1 else t
s=t.find('@router.post(\"/members\", status_code=201)\n'); e=t.find('\n\n@router.get(\"/assignments\")',s) if s!=-1 else -1; t=t[:s]+t[e+2:] if s!=-1 and e!=-1 else t; p.write_text(t); print('PASS patched app/api/club_admin.py')
patch('templates/account/index.html','          <p class="card-copy">Create Manager or Operator accounts. Temporary-password account creation remains available for compatibility until invitation-based onboarding is introduced.</p>\n          <form id="member-form" class="form-stack">\n            <label class="field"><span>Display Name</span><input id="member-name" type="text" placeholder="Example: Erica Smith"></label>\n            <label class="field"><span>Email</span><input id="member-email" type="email" placeholder="name@example.com" required></label>\n            <label class="field"><span>Role</span><select id="member-role"><option value="MANAGER">Manager</option><option value="OPERATOR">Operator</option></select></label>\n            <label class="field"><span>Temporary Password</span><input id="member-password" type="password" placeholder="Minimum 8 characters" required></label>\n            <button class="button button-primary" type="submit">Create Member</button>\n          </form>\n          <div id="member-message" class="form-message" role="status"></div>\n          <div id="members" class="assignment-list"></div>\n','          <p class="card-copy">Invite people to your Club as Managers or Operators. They choose their own password during activation.</p>\n          <form id="member-form" class="form-stack">\n            <label class="field"><span>Display Name</span><input id="member-name" type="text" placeholder="Example: Erica Smith"></label>\n            <label class="field"><span>Email</span><input id="member-email" type="email" placeholder="name@example.com" required></label>\n            <label class="field"><span>Role</span><select id="member-role"><option value="MANAGER">Manager</option><option value="OPERATOR">Operator</option></select></label>\n            <button class="button button-primary" type="submit">Send Invitation</button>\n          </form>\n          <div id="member-message" class="form-message" role="status"></div>\n          <div id="invitation-preview" class="form-message"></div>\n          <h4>Pending Invitations</h4><div id="pending-invitations" class="assignment-list"></div>\n          <h4>Club Members</h4><div id="members" class="assignment-list"></div>\n')
patch('static/js/account.js','let members = [];\nlet teams = [];\n','let members = [];\nlet invitations = [];\nlet teams = [];\n')
patch('static/js/account.js','  [members, teams, games, asgn] = await Promise.all([\n    req(\"/api/admin/members\"),\n    req(\"/api/teams\"),\n    req(\"/api/games\"),\n    req(\"/api/admin/assignments\")\n  ]);\n','  [members, invitations, teams, games, asgn] = await Promise.all([\n    req(\"/api/admin/members\"),\n    req(\"/api/admin/invitations\"),\n    req(\"/api/teams\"),\n    req(\"/api/games\"),\n    req(\"/api/admin/assignments\")\n  ]);\n')
patch('static/js/account.js','function renderSelectors() {\n','function renderInvitations() {\n  const c=$("pending-invitations"); if(!c)return; clear(c);\n  invitations.filter(x=>x.status==="PENDING").forEach(x=>{const row=document.createElement("div");row.className="item";const label=document.createElement("span");label.textContent=`${x.display_name||x.email} · ${x.club_role}`;const r=document.createElement("button");r.type="button";r.textContent="Resend";r.onclick=async()=>{const y=await req(`/api/admin/invitations/${x.id}/resend`,{method:"POST"}); if(y.delivery_preview_url) window.prompt("Local activation URL",y.delivery_preview_url); await load();};const v=document.createElement("button");v.type="button";v.textContent="Revoke";v.onclick=async()=>{await req(`/api/admin/invitations/${x.id}`,{method:"DELETE"});await load();};row.append(label,r,v);c.append(row);});\n}\n\nfunction renderSelectors() {\\n')
patch('static/js/account.js','  renderMembers();\n  renderSelectors();\n','  renderMembers();\n  renderInvitations();\n  renderSelectors();\n')
patch('static/js/account.js','$("member-form")?.addEventListener("submit", async event => {\n  event.preventDefault();\n  $("member-message").textContent = "";\n  try {\n    await req("/api/admin/members", {\n      method: "POST",\n      body: JSON.stringify({\n        display_name: $("member-name").value,\n        email: $("member-email").value,\n        role: $("member-role").value,\n        temporary_password: $("member-password").value\n      })\n    });\n    event.target.reset();\n    await load();\n  } catch (error) {\n    $("member-message").textContent = error.message;\n  }\n});\n','$("member-form")?.addEventListener("submit", async event => {\n  event.preventDefault(); $("member-message").textContent = "";\n  try {\n    const invitation=await req("/api/admin/invitations",{method:"POST",body:JSON.stringify({display_name:$("member-name").value,email:$("member-email").value,role:$("member-role").value})});\n    event.target.reset(); if(invitation.delivery_preview_url) window.prompt("Local activation URL",invitation.delivery_preview_url); await load();\n  } catch(error){ $("member-message").textContent=error.message; }\n});\n')
p=ROOT/'.env.example';t=p.read_text();add='\n# M17-D invitation/email delivery\nPUBLIC_BASE_URL=http://localhost:8000\nINVITATION_TTL_HOURS=72\nEMAIL_DELIVERY_MODE=log\nSMTP_HOST=\nSMTP_PORT=587\nSMTP_USERNAME=\nSMTP_PASSWORD=\nSMTP_USE_TLS=true\nEMAIL_FROM_ADDRESS=\nEMAIL_FROM_NAME=ScoreStreamLive\n'; p.write_text(t if 'EMAIL_DELIVERY_MODE=' in t else t+add); print('PASS patched .env.example')
print('M17-D implementation registration applied successfully.')
