#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."&&pwd)";cd "$ROOT";BASE_URL="${BASE_URL:-http://192.168.12.133:8000}";BASE_URL="${BASE_URL%/}";VALIDATION_MODE="${VALIDATION_MODE:-local}";P=0;F=0;X=();T=$(mktemp);R=$(mktemp);trap 'rm -f "$T" "$R"' EXIT;ok(){ P=$((P+1));};bad(){ F=$((F+1));X+=("$1");}
echo "[1/7] Checking application health...";for p in /health/live /health/ready;do c=$(curl -sS -o /dev/null -w "%{http_code}" "$BASE_URL$p"||true);[[ $c == 200 ]]&&ok||bad "$p HTTP $c";done
echo "[2/7] Creating Team fixture...";c=$(curl -sS -o "$T" -w "%{http_code}" -X POST "$BASE_URL/api/teams" -H 'Content-Type: application/json' --data "{\"name\":\"M13-D Validation $(date +%s)\"}"||true);ID=$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1])).get("id",""))' "$T" 2>/dev/null||true);[[ $c == 201&& -n $ID ]]&&ok||bad "Team fixture failed"
echo "[3/7] Creating Player...";c=$(curl -sS -o "$T" -w "%{http_code}" -X POST "$BASE_URL/api/players" -H 'Content-Type: application/json' --data "{\"team_id\":\"$ID\",\"first_name\":\"M13D\",\"last_name\":\"Create\",\"jersey_number\":21}"||true);PID=$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1])).get("id",""))' "$T" 2>/dev/null||true);[[ $c == 201&& -n $PID ]]&&ok||bad "Player create failed"
echo "[4/7] Editing Player and verifying ownership...";c=$(curl -sS -o "$T" -w "%{http_code}" -X PATCH "$BASE_URL/api/players/$PID" -H 'Content-Type: application/json' --data '{"first_name":"M13D","last_name":"Edited","jersey_number":22}'||true);[[ $c == 200 ]]&&ok||bad "Player edit failed";python3 - "$T" "$ID" <<'PY'&&ok||bad "Persisted Player incorrect"
import json,sys
d=json.load(open(sys.argv[1]));assert d["team_id"]==sys.argv[2] and d["last_name"]=="Edited" and d["jersey_number"]==22
PY
echo "[5/7] Checking M13-D UI contract...";curl -fsS "$BASE_URL/teams/$ID">"$T"||true;for m in 'M13-D' 'id="add-player"' 'id="player-modal"' 'edit-player';do grep -Fq "$m" "$T"&&ok||bad "Missing UI $m";done
echo "[6/7] Checking protected boundaries...";if [[ $VALIDATION_MODE == local ]];then grep -Fq 'method:"POST"' static/js/teams/detail.js&&ok||bad "POST missing";grep -Fq 'method:"PATCH"' static/js/teams/detail.js&&ok||bad "PATCH missing";if grep -Eq 'method:"(DELETE|PUT)"' static/js/teams/detail.js;then bad "Out-of-scope mutation";else ok;fi;if grep -A10 'class PlayerUpdate' app/schemas/player.py|grep -Fq 'team_id';then bad "PlayerUpdate permits reassignment";else ok;fi;else for _ in {1..4};do ok;done;fi
echo "[7/7] Running M13-C cumulative regression silently...";set +e;BASE_URL="$BASE_URL" VALIDATION_MODE="$VALIDATION_MODE" ./scripts/validate_m13c.sh>"$R" 2>&1;RC=$?;set -e;[[ $RC == 0 ]]||X+=("M13-C cumulative regression failed")
echo "========================================";echo "ScoreStreamLive M13-D Validation Summary";echo "BASE_URL: $BASE_URL";echo "MODE: $VALIDATION_MODE";echo "========================================";[[ $F == 0 ]]&&echo "M13-D ............... PASS   $P passed / 0 failed"||echo "M13-D ............... FAIL   $P passed / $F failed";[[ $RC == 0 ]]&&echo "M13-C cumulative .... PASS"||echo "M13-C cumulative .... FAIL";echo "========================================";if [[ $F == 0&&$RC == 0 ]];then echo "OVERALL ............. PASS";echo "Failed Components: None";echo "========================================";echo "M13-D AUTOMATED ACCEPTANCE = PASS";exit 0;fi;echo "OVERALL ............. FAIL";echo "Failed Components:";printf '%s\n' "${X[@]}"|awk 'NF&&!s[$0]++{print "- "$0}';exit 1
